USE EMPRESA_DB;

-- HAVING
SELECT NumeroPedido, COUNT(*) AS VENDAS FROM TB_DETALHE_PEDIDO
WHERE NumeroPedido IN (10248, 10249, 10250, 10251)
GROUP BY NumeroPedido HAVING COUNT(*) = 3;

SELECT NumeroPedido, COUNT(*) AS VENDAS FROM TB_DETALHE_PEDIDO
GROUP BY NumeroPedido HAVING COUNT(*) < 3;


-- inserting duplicity
INSERT INTO TB_CLIENTE
(ClienteId, NomeCompleto, Contato, Cargo)
VALUES
('OPOPO', 'MARCOS ALBERTO', 'MARIA JOAQUINA', 'VENDEDOR');

-- REMOVING DUPLICITY WITH HAVING AND GROUP BY
SELECT NomeCompleto, COUNT(NomeCompleto) FROM TB_CLIENTE
GROUP BY NomeCompleto
HAVING COUNT(NomeCompleto) > 1 ;

SELECT * FROM TB_CLIENTE WHERE NomeCompleto = 'MARCOS ALBERTO';

DELETE TB_CLIENTE WHERE ClienteId = 'OPOPO';