USE EMPRESA_DB;

-- MAX
SELECT MAX(PRECO) AS PMAX FROM TB_DETALHE_PEDIDO
WHERE NumeroPedido = 10248;

-- MIN
SELECT MIN(PRECO) AS PMIN FROM TB_DETALHE_PEDIDO
WHERE NumeroPedido = 10248;

-- AVERAGE
SELECT AVG(PRECO) AS PAVG FROM TB_DETALHE_PEDIDO
WHERE NumeroPedido = 10248;

SELECT NumeroPedido, AVG(PRECO) FROM TB_DETALHE_PEDIDO
GROUP BY NumeroPedido;

-- SUM
SELECT NumeroPedido, SUM(PRECO) AS TOTAL FROM TB_DETALHE_PEDIDO
GROUP BY NumeroPedido;

-- COUNT
SELECT NumeroPedido, COUNT(*) AS QUANTIDADE FROM TB_DETALHE_PEDIDO
GROUP BY NumeroPedido;