USE EMPRESA_DB;

-- CORRELTED SUBQUERY (relaciona a query externa com a interna)
SELECT * FROM TB_CLIENTE CLI
WHERE CLI.CARGO IN (
	SELECT F.CARGO FROM TB_FUNCIONARIO F
	WHERE F.Cargo = CLI.Cargo)

-- EXISTS / NOT EXISTS
SELECT CLI.* FROM TB_CLIENTE CLI
WHERE NOT EXISTS(
	SELECT * FROM TB_PEDIDO P
	WHERE P.ClienteId = CLI.ClienteId AND
	P.DataPedido BETWEEN '2020-07-01' AND '2020-07-31');

-- UPDATE WITH SUBQUERY
UPDATE TB_PRODUTO SET Preco -= 1
WHERE CategoriaId = (
	SELECT CategoriaId FROM TB_CATEGORIA
	WHERE Descricao = 'Bebidas');

SELECT * FROM TB_PRODUTO
WHERE CategoriaId = (
	SELECT CategoriaId FROM TB_CATEGORIA
	WHERE Descricao = 'Bebidas');

-- DELETE WITH SUBQUERY
DELETE FROM TB_PEDIDO
WHERE FuncionarioId = (
	SELECT FuncionarioId FROM TB_FUNCIONARIO
	WHERE Cargo = 'Vice-Presidente de Vendas');