
CREATE DATABASE EMPRESA_DB;
GO
USE EMPRESA_DB;
GO
CREATE TABLE TB_CATEGORIA
(
    CategoriaId INT NOT NULL,
	Descricao VARCHAR(35) NOT NULL,
	CONSTRAINT PK_TB_CATEGORIA_CATEGORIAID PRIMARY KEY(CategoriaId)

);
GO
CREATE TABLE TB_CLIENTE
(
	ClienteId CHAR(5) NOT NULL,
	NomeCompleto VARCHAR(70) NOT NULL,
	Contato VARCHAR(70) NOT NULL,
	Cargo VARCHAR(40) NOT NULL,
	CONSTRAINT PK_TB_CLIENTE_CLIENTEID PRIMARY KEY(ClienteId)
);
GO
CREATE TABLE TB_FUNCIONARIO
(
	FuncionarioId INT NOT NULL,
	NomeCompleto VARCHAR(70) NOT NULL,
	Cargo VARCHAR(50) NOT NULL,
	DataNascimento DATETIME2 NOT NULL,
	Salario MONEY NOT NULL,
	CONSTRAINT PK_TB_FUNCIONARIO_FUNCIONARIOID PRIMARY KEY(FuncionarioId)
);
GO
CREATE TABLE TB_FORNECEDOR
(
	FornecedorId INT NOT NULL,
	Empresa VARCHAR(70) NOT NULL,
	Contato VARCHAR(70) NOT NULL,
	Cargo VARCHAR(45) NOT NULL,
	CONSTRAINT PK_TB_FORNECEDOR_FORNECEDORID PRIMARY KEY(FornecedorId)
);
GO
CREATE TABLE TB_ENDERECO
(
	EnderecoId INT IDENTITY(1,1) NOT NULL,
	Logradouro VARCHAR(80) NOT NULL,
	Cidade VARCHAR(40) NOT NULL,
	CEP VARCHAR(40) NOT NULL,
	Pais VARCHAR(35) NOT NULL,
	Regiao VARCHAR(25) NULL,
	Telefone VARCHAR(35) NULL,
	ClienteId CHAR(5) NULL,
	FuncionarioId INT NULL,
	FornecedorId INT NULL,
	CONSTRAINT PK_TB_ENDERECO_ENDERECOID PRIMARY KEY(EnderecoId),
	CONSTRAINT FK_TB_ENDERECO_TB_CLIENTE_CLIENTEID FOREIGN KEY(ClienteId)
	REFERENCES TB_CLIENTE(ClienteId),
	CONSTRAINT FK_TB_ENDERECO_TB_FUNCIONARIO FOREIGN KEY(FuncionarioId)
	REFERENCES TB_FUNCIONARIO(FuncionarioId),
	CONSTRAINT FK_TB_ENDERECO_TB_FORNECEDOR FOREIGN KEY(FornecedorId)
	REFERENCES TB_FORNECEDOR(FornecedorId)
);
GO
CREATE TABLE TB_PEDIDO
(
	NumeroPedido INT NOT NULL,
	ClienteId CHAR(5) NOT NULL,
	FuncionarioId INT NOT NULL,
	DataPedido DATETIME2 NOT NULL,
	DataEntrega DATETIME2 NOT NULL,
	Frete MONEY NOT NULL,
	CONSTRAINT PK_TB_PEDIDO_NUMEROPEDIDO PRIMARY KEY(NumeroPedido),
	CONSTRAINT FK_TB_PEDIDO_TB_CLIENTE FOREIGN KEY(ClienteId)
	REFERENCES TB_CLIENTE(ClienteId),
	CONSTRAINT FK_TB_PEDIDO_TB_FUNCIONARIO FOREIGN KEY(FuncionarioId)
	REFERENCES TB_FUNCIONARIO(FuncionarioId)
);
GO
CREATE TABLE TB_PRODUTO
(
	ProdutoId INT NOT NULL,
	Descricao VARCHAR(70) NOT NULL,
	Preco MONEY NOT NULL,
	Unidades INT NOT NULL,
	Descontinuado BIT DEFAULT 0,
	FornecedorId INT NOT NULL,
	CategoriaId INT NOT NULL,
	CONSTRAINT PK_TB_PRODUTO_PRODUTOID PRIMARY KEY(ProdutoId),
	CONSTRAINT FK_TB_PRODUTO_TB_FORNECEDOR FOREIGN KEY(FornecedorId)
	REFERENCES TB_FORNECEDOR(FornecedorId),
	CONSTRAINT FK_TB_PRODUTO_TB_CATEGORIA FOREIGN KEY(CategoriaId)
	REFERENCES TB_CATEGORIA(CategoriaId)
);
GO
CREATE TABLE TB_DETALHE_PEDIDO
(
	NumeroPedido INT NOT NULL,
	ProdutoId INT NOT NULL,
	Preco MONEY NOT NULL,
	Quantidade INT NOT NULL,
	Desconto DECIMAL(3,2) DEFAULT 0,
	CONSTRAINT PK_DETALHE_PEDIDO PRIMARY KEY(NumeroPedido, ProdutoId),
	CONSTRAINT FK_DETALHE_PEDIDO_TB_PRODUTO FOREIGN KEY(ProdutoId)
	REFERENCES TB_PRODUTO(ProdutoId),
	CONSTRAINT FK_TB_DETALHE_PEDIDO_TB_PEDIDO FOREIGN KEY(NumeroPedido)
	REFERENCES TB_PEDIDO(NumeroPedido)
);