
-- MATH FUNCTIONS

-- CEILING (ARREDONDA PARA O MAIOR)
PRINT CEILING(5.3278);

-- FLOOR (ARREDONDA PARA O MENOR)
PRINT FLOOR(5.3278);

-- GERADOR DE NÚMEROS PSEUDO-ALEATÓRIOS (POSSUI SEED)
PRINT RAND(); -- SEED = CLOCK DO PC

-- ROUND (ARREDONDAMENTO)
PRINT ROUND(50032.03217, 2); -- ARREDONDA AS 2 ÚLTIMAS CASAS);

PRINT CONVERT(DECIMAL(15, 3), 123.31259697);

-- POWER
PRINT POWER(4, 2);
PRINT POWER(2, 16);