USE EMPRESA_DB;


-- DATE FUNCTIONS

-- SYSTEM DATETIME
SELECT SYSDATETIME() AS [SYSTEM DATETIME];
SELECT SYSDATETIMEOFFSET() AS [SYSTEM DATETIME OFFSET];
SELECT SYSUTCDATETIME() AS [GREENWICH DATETIME];

SELECT CURRENT_TIMESTAMP AS [CURRENT TIME WITHOUT PRECISION];
SELECT GETDATE();
SELECT GETUTCDATE() AS [GREENWICH TIME WITHOUT PRECISION];

-- PARTES DE DATAS
SELECT DATENAME(YEAR, GETDATE()) AS ANO; -- RETORNA NVARCHAR
SELECT DATENAME(MONTH, GETDATE()) AS MÊS; -- RETORNA NVARCHAR
SELECT DATENAME(DAY, GETDATE()) AS DIA; -- RETORNA NVARCHAR
SELECT DATENAME(WEEK, GETDATE()) AS SEMANA; -- RETORNA NVARCHAR
SELECT DATENAME(WEEKDAY, GETDATE()) AS [DIA DA SEMANA]; -- RETORNA NVARCHAR

SELECT DATEPART(WEEKDAY, GETDATE()) AS [DIA DA SEMANA]; -- RETORNA INT
SELECT DATEPART(MONTH, GETDATE()) AS [MÊS]; -- RETORNA INT

SELECT DAY(GETDATE()) AS [DIA DE UMA DATA]; -- RETORNA INT
SELECT YEAR(GETDATE()) AS [ANO DE UMA DATA]; -- RETORNA INT

-- DIFERENÇAS DE DATAS
SELECT DATEDIFF_BIG(MICROSECOND, '2000-01-01', '2000-03-03') [DIFERENÇA EM MICROSEGUNDOS]; -- RETORNA UM BIGINT
SELECT DATEDIFF(SECOND, '2000-01-01', '2000-03-03') [DIFERENÇA EM SEGUNDOS]; -- RETORNA INT
SELECT DATEDIFF(MINUTE, '2000-01-01', '2000-03-03') [DIFERENÇA EM MINUTOS]; -- RETORNA INT
SELECT DATEDIFF(HOUR, '2000-01-01', '2000-03-03') [DIFERENÇA EM HORAS]; -- RETORNA INT
SELECT DATEDIFF(MONTH, '2000-01-01', '2000-03-03') [DIFERENÇA EM MESES]; -- RETORNA INT
SELECT DATEDIFF(YEAR, '2000-01-01', '2010-03-03') [DIFERENÇA EM ANOS]; -- RETORNA INT
SELECT DATEDIFF(YEAR, '2020-01-01', '2010-03-03') [SE INVERTER RETORNA NEGATIVO]; -- RETORNA INT

-- ADICIONAR DATAS
SELECT DATEADD(DAY, 10, GETDATE());
SELECT DATEADD(MONTH, 4, GETDATE());
SELECT DATEADD(YEAR, 5, GETDATE());

-- VALIDA DATA
SELECT ISDATE('2000-13-44'); -- RETORNA ZERO(0) => FALSO
SELECT ISDATE('2000-12-04'); -- RETORNA UM(1) => VERDADEIRO
